version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: hugo/tp-cloud
    networks:
      - frontend
      - backend
    environment:
      - DB_HOST=tp-cloud-mysql-app
      - DB_USER=hugo
      - DB_PASS=borini
      - DB_NAME=tp-cloud
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:8005"
    container_name: tp-cloud-nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=hugo
      - MYSQL_PASSWORD=borini
      - MYSQL_DATABASE=tp-cloud
    container_name: tp-cloud-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=tp-cloud-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: tp-cloud-phpmyadmin-app
networks:
  frontend:
  backend: